name: cgapp
description: A new Flutter project
publish_to: "none"

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.10.6
  firebase_auth: ^3.3.6
  cloud_firestore: ^3.1.5

  shared:
    path: ../shared  # Ajuste o caminho conforme necessÃ¡rio

  auto_route: ^4.4.0
  mobile_scanner: ^0.0.1

flutter:
  uses-material-design: true
